CreateThread(function()
	TriggerEvent('chat:addSuggestion', '/me', 'Roleplay action.', {{name = 'action', help = 'Describe your roleplay action.'}})
	TriggerEvent('chat:addSuggestion', '/my', 'Roleplay action.', {{name = 'action', help = 'Describe your roleplay action.'}})
	TriggerEvent('chat:addSuggestion', '/do', 'Roleplay action.', {{name = 'description', help = 'Describe the scene or action.'}})
	TriggerEvent('chat:addSuggestion', '/say', 'Say something.', {{name = 'message', help = 'The message you want to say.'}})
	TriggerEvent('chat:addSuggestion', '/sayto', 'Say something to a specific player.', {{name = 'Player ID', help = 'The ID of the player.'}, {name = 'message', help = 'The message you want to say.'}})
	TriggerEvent('chat:addSuggestion', '/b', 'Local out of character chat.', {{name = 'message', help = 'The message you want to say.'}})
	TriggerEvent('chat:addSuggestion', '/blow', 'Low proximity local out of character chat.', {{name = 'message', help = 'The message you want to say.'}})
	TriggerEvent('chat:addSuggestion', '/bto', 'Local out of character chat to a specific player.', {{name = 'Player ID', help = 'The ID of the player.'}, {name = 'message', help = 'The message you want to say.'}})
	TriggerEvent('chat:addSuggestion', '/blowto', 'Low proximity local out of character chat to a specific player.', {{name = 'Player ID', help = 'The ID of the player.'}, {name = 'message', help = 'The message you want to say.'}})
	TriggerEvent('chat:addSuggestion', '/melow', 'Low proximity roleplay action.', {{name = 'action', help = 'Describe your roleplay action.'}})
	TriggerEvent('chat:addSuggestion', '/mylow', 'Roleplay action.', {{name = 'action', help = 'Describe your roleplay action.'}})
	TriggerEvent('chat:addSuggestion', '/dolow', 'Low proximity roleplay action.', {{name = 'description', help = 'Describe the scene or action.'}})
	TriggerEvent('chat:addSuggestion', '/low', 'Say something in a low proximity.', {{name = 'message', help = 'The message you want to say.'}})
	TriggerEvent('chat:addSuggestion', '/lowto', 'Say something in a low proximity to a specific player.', {{name = 'Player ID', help = 'The ID of the player.'}, {name = 'message', help = 'The message you want to say.'}})
	TriggerEvent('chat:addSuggestion', '/whisper', 'Whisper something.', {{name = 'message', help = 'The message you want to whisper.'}})
	TriggerEvent('chat:addSuggestion', '/whisperto', 'Whisper something to a specific player.', {{name = 'Player ID', help = 'The ID of the player.'}, {name = 'message', help = 'The message you want to whisper.'}})
	TriggerEvent('chat:addSuggestion', '/shout', 'Shout something.', {{name = 'message', help = 'The message you want to shout.'}})
	TriggerEvent('chat:addSuggestion', '/shoutto', 'Shout something to a specific player.', {{name = 'Player ID', help = 'The ID of the player.'}, {name = 'message', help = 'The message you want to shout.'}})
	TriggerEvent('chat:addSuggestion', '/pm', 'Send a private message.', {{name = 'Player ID or Name', help = 'The ID or name of the player.'}, {name = 'message', help = 'The message you want to send.'}})
	TriggerEvent('chat:addSuggestion', '/id', 'Find a player by ID or name.', {{name = 'Player ID or Name', help = 'The ID or name of the player.'}})
	TriggerEvent('chat:addSuggestion', '/flipcoin', 'Flip a coin to get heads or tails.')
	TriggerEvent('chat:addSuggestion', '/dice', 'Roll dice.', {{name = 'number', help = 'Number of dice to roll (1-3).'}})
	TriggerEvent('chat:addSuggestion', '/report', 'Submit a report.', {{name = 'message', help = 'The message you want to report.'}})
	TriggerEvent('chat:addSuggestion', '/acceptreport', 'Accept a report.', {{name = 'report ID', help = 'The ID of the report to accept.'}})
	TriggerEvent('chat:addSuggestion', '/trashreport', 'Trash a report.', {{name = 'report ID', help = 'The ID of the report to trash.'}})
	TriggerEvent('chat:addSuggestion', '/listreports', 'List all pending reports.')
	TriggerEvent('chat:addSuggestion', '/helpme', 'Request help from testers.', {{name = 'question', help = 'The question you want to ask.'}})
	TriggerEvent('chat:addSuggestion', '/accepthelpme', 'Accept a help request.', {{name = 'request ID', help = 'The ID of the help request to accept.'}})
	TriggerEvent('chat:addSuggestion', '/trashhelpme', 'Trash a help request.', {{name = 'request ID', help = 'The ID of the help request to trash.'}})
	TriggerEvent('chat:addSuggestion', '/listhelpmes', 'List all pending help requests.')
	TriggerEvent('chat:addSuggestion', '/stats', 'Show your character statistics.')
	TriggerEvent('chat:addSuggestion', '/clearchat', 'Clear your chat.')
end)

AddEventHandler('onResourceStop', function(resource)
	if resource == GetCurrentResourceName() then
		TriggerEvent('chat:removeSuggestion', '/me')
		TriggerEvent('chat:removeSuggestion', '/my')
		TriggerEvent('chat:removeSuggestion', '/do')
		TriggerEvent('chat:removeSuggestion', '/say')
		TriggerEvent('chat:removeSuggestion', '/sayto')
		TriggerEvent('chat:removeSuggestion', '/b')
		TriggerEvent('chat:removeSuggestion', '/blow')
		TriggerEvent('chat:removeSuggestion', '/bto')
		TriggerEvent('chat:removeSuggestion', '/blowto')
		TriggerEvent('chat:removeSuggestion', '/melow')
		TriggerEvent('chat:removeSuggestion', '/mylow')
		TriggerEvent('chat:removeSuggestion', '/dolow')
		TriggerEvent('chat:removeSuggestion', '/low')
		TriggerEvent('chat:removeSuggestion', '/lowto')
		TriggerEvent('chat:removeSuggestion', '/whisper')
		TriggerEvent('chat:removeSuggestion', '/whisperto')
		TriggerEvent('chat:removeSuggestion', '/shout')
		TriggerEvent('chat:removeSuggestion', '/shoutto')
		TriggerEvent('chat:removeSuggestion', '/pm')
		TriggerEvent('chat:removeSuggestion', '/id')
		TriggerEvent('chat:removeSuggestion', '/flipcoin')
		TriggerEvent('chat:removeSuggestion', '/dice')
		TriggerEvent('chat:removeSuggestion', '/report')
		TriggerEvent('chat:removeSuggestion', '/acceptreport')
		TriggerEvent('chat:removeSuggestion', '/trashreport')
		TriggerEvent('chat:removeSuggestion', '/listreports')
		TriggerEvent('chat:removeSuggestion', '/helpme')
		TriggerEvent('chat:removeSuggestion', '/accepthelpme')
		TriggerEvent('chat:removeSuggestion', '/trashhelpme')
		TriggerEvent('chat:removeSuggestion', '/listhelpmes')
		TriggerEvent('chat:removeSuggestion', '/stats')
		TriggerEvent('chat:removeSuggestion', '/clearchat')
	end
end)

RegisterNetEvent('chat:clear')
AddEventHandler('chat:clear', function()
	TriggerEvent('chat:clear')
end)